repository: JoshOBrien/exiftoolr

theme: jekyll-theme-minimal

title: exiftoolr
description: Read and modify EXIF data from R

show_downloads: true


gems:
  - jekyll-github-metadata

# 7212bbb605ba62bdf3eb6dac78c27394e0fb5d6d
