theme: jekyll-theme-minimal

pygments: true


title: exiftoolr
description: Read and modify EXIF data from R


show_downloads: true

## Use pandoc for md
markdown: pandoc
pandoc:
  format: html5
  extensions:
    - smart
    - mathjax
    - highlight-style: pygments
