source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!

# This is the default theme for new Jekyll sites. You may change this to anything you like.
# gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins
# gem "jekyll-github-metadata", group: :jekyll_plugins
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
## Whenever GitHub prompts me about a vulnerability found in my
## lockfile, follow its instructions to modify the version of nokogiri
## below and then locally run `bundle update nokogiri`
gem 'nokogiri', '>= 1.13.4'
gem 'json', '>= 2.3.0'
gem 'kramdown', '>= 2.3.0'
gem "addressable", ">= 2.8.0"

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", ">= 0.10"
end
